name: flutter_task_management_app

description: A Flutter app for managing tasks with SQLite storage.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.4.1
  path_provider: ^2.0.11
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  provider: ^6.0.5
  lottie: ^3.1.3
  flutter_slidable: ^3.1.1
  animate_do: ^3.3.4
  panara_dialogs: ^0.1.2
  ftoast: ^2.0.0
  path: ^1.9.0
  sqflite_common_ffi: ^2.0.0+1
  flutter_local_notifications: ^18.0.0 # Added for local notifications
  timezone: ^0.9.0 # Added for timezone support
  logger: ^2.4.0 # Add this line
  permission_handler: ^11.3.1
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/1.png
