name: flutter_task_management_app

description: A Flutter app for managing tasks with SQLite storage.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  provider: ^6.0.5
  lottie: ^1.4.0
  flutter_slidable: ^0.6.0
  animate_do: ^3.3.4
  panara_dialogs: ^0.1.2
  ftoast: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/

  # Uncomment the following lines if you want to use custom fonts in your app
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
