name: task_manager_updated
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev.
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Project dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_storage: ^2.0.3
  get: ^4.6.5
  intl: ^0.18.1
  google_fonts: ^3.0.1
  flutter_local_notifications: ^9.9.1
  flutter_native_timezone: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter specific settings
flutter:
  uses-material-design: true

  assets:
    - images/

  # Custom fonts can be added here
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
